// Code generated by "stringer -type=Op"; DO NOT EDIT.

package code

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PUSH-1]
	_ = x[ADD_INT-2]
	_ = x[SUB_INT-3]
	_ = x[MUL_INT-4]
	_ = x[DIV_INT-5]
	_ = x[LT_INT-6]
	_ = x[LTE_INT-7]
	_ = x[GT_INT-8]
	_ = x[GTE_INT-9]
	_ = x[ADD_FLOAT-10]
	_ = x[SUB_FLOAT-11]
	_ = x[MUL_FLOAT-12]
	_ = x[DIV_FLOAT-13]
	_ = x[AND_BOOL-14]
	_ = x[OR_BOOL-15]
	_ = x[EQ-16]
	_ = x[NEQ-17]
	_ = x[LT_FLOAT-18]
	_ = x[LTE_FLOAT-19]
	_ = x[GT_FLOAT-20]
	_ = x[GTE_FLOAT-21]
	_ = x[ADD_STRING-22]
	_ = x[JUMP-23]
	_ = x[JUMP_FALSE-24]
	_ = x[RETURN-25]
	_ = x[RETURN_VALUE-26]
	_ = x[CALL-27]
	_ = x[STORE_GLOBAL-28]
	_ = x[STORE_LOCAL-29]
	_ = x[LOAD_GLOBAL-30]
	_ = x[LOAD_LOCAL-31]
	_ = x[LOAD_FREE-32]
	_ = x[CLOSURE-33]
	_ = x[ARRAY-34]
	_ = x[HASH-35]
	_ = x[INDEX-36]
	_ = x[ACCESS-37]
	_ = x[TO_FLOAT-38]
	_ = x[CLASS-39]
	_ = x[BUILTIN-40]
}

const _Op_name = "PUSHADD_INTSUB_INTMUL_INTDIV_INTLT_INTLTE_INTGT_INTGTE_INTADD_FLOATSUB_FLOATMUL_FLOATDIV_FLOATAND_BOOLOR_BOOLEQNEQLT_FLOATLTE_FLOATGT_FLOATGTE_FLOATADD_STRINGJUMPJUMP_FALSERETURNRETURN_VALUECALLSTORE_GLOBALSTORE_LOCALLOAD_GLOBALLOAD_LOCALLOAD_FREECLOSUREARRAYHASHINDEXACCESSTO_FLOATCLASSBUILTIN"

var _Op_index = [...]uint16{0, 4, 11, 18, 25, 32, 38, 45, 51, 58, 67, 76, 85, 94, 102, 109, 111, 114, 122, 131, 139, 148, 158, 162, 172, 178, 190, 194, 206, 217, 228, 238, 247, 254, 259, 263, 268, 274, 282, 287, 294}

func (i Op) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_Op_index)-1 {
		return "Op(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Op_name[_Op_index[idx]:_Op_index[idx+1]]
}
