// Code generated by "stringer -type=Op"; DO NOT EDIT.

package code

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PUSH-1]
	_ = x[ADD_INT-2]
	_ = x[SUB_INT-3]
	_ = x[MUL_INT-4]
	_ = x[DIV_INT-5]
	_ = x[LT_INT-6]
	_ = x[LTE_INT-7]
	_ = x[GT_INT-8]
	_ = x[GTE_INT-9]
	_ = x[ADD_FLOAT-10]
	_ = x[SUB_FLOAT-11]
	_ = x[MUL_FLOAT-12]
	_ = x[DIV_FLOAT-13]
	_ = x[AND_BOOL-14]
	_ = x[OR_BOOL-15]
	_ = x[EQ-16]
	_ = x[NEQ-17]
	_ = x[LT_FLOAT-18]
	_ = x[LTE_FLOAT-19]
	_ = x[GT_FLOAT-20]
	_ = x[GTE_FLOAT-21]
	_ = x[ADD_STRING-22]
	_ = x[JUMP-23]
	_ = x[JUMP_FALSE-24]
	_ = x[RETURN-25]
	_ = x[CALL-26]
	_ = x[STORE_GLOBAL-27]
	_ = x[LOAD_GLOBAL-28]
	_ = x[STORE_LOCAL-29]
	_ = x[LOAD_LOCAL-30]
}

const _Op_name = "PUSHADD_INTSUB_INTMUL_INTDIV_INTLT_INTLTE_INTGT_INTGTE_INTADD_FLOATSUB_FLOATMUL_FLOATDIV_FLOATAND_BOOLOR_BOOLEQNEQLT_FLOATLTE_FLOATGT_FLOATGTE_FLOATADD_STRINGJUMPJUMP_FALSERETURNCALLSTORE_GLOBALLOAD_GLOBALSTORE_LOCALLOAD_LOCAL"

var _Op_index = [...]uint8{0, 4, 11, 18, 25, 32, 38, 45, 51, 58, 67, 76, 85, 94, 102, 109, 111, 114, 122, 131, 139, 148, 158, 162, 172, 178, 182, 194, 205, 216, 226}

func (i Op) String() string {
	i -= 1
	if i < 0 || i >= Op(len(_Op_index)-1) {
		return "Op(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Op_name[_Op_index[i]:_Op_index[i+1]]
}
